### ISSUE TITLE
Generated metadata with a link to a non-existent path

### ISSUE THREAD

**Issue by erroneous0ne** [elasticio/soap-component#23]
# Component Bug Report

### Useful Links

- [Link](https://support.elastic.io/a/tickets/9175) to the SQUIZ ticket.
- [Link](https://elasticio.slack.com/archives/G8YQQ9PMM/p1731655479855749) to the internal Slack conversation.

## Description

SQUIZ reported a problem with the SOAP component, when it tries to load the Mapping section. SQUIZ gets a console error which crashes the UI, so you need to reload it, here is the [flow](https://app.connect.squiz.cloud/c/5eb0f972183d6f00129cd119/w/6735361894c6f30012c2c8b1/designer/67356ed094c6f30012cfd715/draft) draft.
The WSDL URL they use: https://cloud.timeedit.net/soap/3/au_cit/wsdl

From the given scheme logs - there is a link to a non-existent path in the generated metadata
![image](https://github.com/user-attachments/assets/538a7ce8-d6fa-4d24-a102-f51d4c7c8320)

## Component Version

1.2.9

## Steps to Reproduce

1. Create a SOAP step with the `Call` action
2. Set the following Configuration
![image](https://github.com/user-attachments/assets/52c6e1e6-a228-4912-9f71-0168956641be)
3. Load the Mapping section

## Actual Result

The soap component throws a console JS error at the Mapping which crashes the UI and prevents the flow from being built. 

> Note: The JS error was successfully reproduced on the SQUIZ US and Sparrow tenants, e.g. on Westeros you will get an `Execution timeout`.

Console error:
```
Error: Invalid reference: urn:jsonschema:se:timeedit:timeedit3:version3:Fieldids (unknown schema URI)
    at c (frontend.61b7f11.min.js:47:4664)
    at e (frontend.61b7f11.min.js:47:5771)
    at f (frontend.61b7f11.min.js:47:6550)
    at f (frontend.61b7f11.min.js:47:6765)
    at f (frontend.61b7f11.min.js:47:6765)
    at f (frontend.61b7f11.min.js:47:6765)
    at f (frontend.61b7f11.min.js:47:6765)
    at f (frontend.61b7f11.min.js:47:6765)
    at Object.m [as toFieldsTree] (frontend.61b7f11.min.js:47:8324)
    at h.<anonymous> (frontend.61b7f11.min.js:41:15038) 'Error: Invalid reference: urn:jsonschema:se:timeedit:timeedit3:version3:Fieldids (unknown schema URI)\n    at c (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:4664)\n    at e (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:5771)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6550)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6765)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6765)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6765)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6765)\n    at f (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:6765)\n    at Object.m [as toFieldsTree] (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:47:8324)\n    at h.<anonymous> (https://app.connect.squiz.cloud/frontend.61b7f11.min.js:41:15038)'
```

## Expected Result

Correctly generated metadata

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/soap-component/releases/tag/1.2.10
